version: '3.6'

services:
  api:
    build: 
      context: .
    container_name: api
    depends_on:
      - db
    ports:
      - 5555:5555
    networks:
      - backend 

  db:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - ./.docker/db-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2020-11-10T21-02-24Z
    container_name: minio
    depends_on:
      - db
    environment:
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: ${MINIO_BUCKET}  
    ports:
      - "9000:9000"
    networks:
      - backend
    volumes:
      - ./storage/minio:/data
    command: server /data    

networks:
  backend:
    driver: bridge

volumes:
  db-data:
