version: '3.6'

services:
  db:
    image: postgres:13-alpine
    restart: always
    container_name: postgres-artista
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: PJC
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - ./.docker/db-data:/var/lib/postgresql/data

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: artista-api
    depends_on:
      - db
    ports:
      - 5555:5555
    networks:
      - backend
  
  minio:
    image: minio/minio
    container_name: minio-artista
    environment:
      MINIO_BUCKET: album-artista-pjc
      MINIO_ENDPOINT: play.min.io
      MINIO_ACCESS_KEY: Q3AM3UQ867SPQQA43P2F
      MINIO_SECRET_KEY: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
    ports:
      - "9000:9000"
    volumes:
      - ./storage/minio:/data
    command: server --address 0.0.0.0:9000 /data      

networks:
  backend:
    driver: bridge

volumes:
  db-data:
